### ISSUE TITLE
Specify black version

### ISSUE THREAD

**Issue by theferrit32** [biocommons/biocommons.seqrepo#125]
https://github.com/biocommons/biocommons.seqrepo/blob/be604069b17a6e4b50b76b4b62153220ec566441/setup.cfg#L22

Formatting rules can vary slightly between black versions. 

Doesn't really matter but probably take the biocommons.example one `black ~= 22.3`. It is compatible with (or is) the version @reece ran in https://github.com/biocommons/biocommons.seqrepo/commit/7cc7f374ad359ba6654e501c5ed92e8e18ef8f17 because no files are flagged by `black --check ./src/`

https://github.com/biocommons/biocommons.example/blob/9aa8d987587ca50f9ac2a1ba3bfbf5e212344686/pyproject.toml#L27

**Comment by reece** [comment]
This issue was closed by stalebot. It has been reopened to give more time for community review.  See [biocommons coding guidelines](https://biocommons.org/contributing/coding-guidelines/) for stale issue and pull request policies.  This resurrection is expected to be a onos.environ["GITHUB_TOKEN"]e-time event.

**Comment by theferrit32** [comment]
Closed in https://github.com/biocommons/biocommons.seqrepo/commit/26751d41cb78216eade45833ffd90755c02a5876
