### ISSUE TITLE
Ensembl transcript ENST00000617537.5 sequence is wrong (88x larger than it should be)

### ISSUE THREAD

**Issue by davmlaw** [biocommons/biocommons.seqrepo#170]
https://asia.ensembl.org/Homo_sapiens/Transcript/Summary?db=core;g=ENSG00000136250;r=7:36512941-36724494;t=ENST00000617537

Web page Reports that the sequence is 2385 bases long

Ensembl API is in agreement:

```
In [25]: import requests
In [26]: url = "https://rest.ensembl.org/sequence/id/ENST00000617537?type=cdna"
In [27]: r = requests.get(url, headers={"Content-Type": "application/json"}, timeout=60)
In [28]: len(r.json()["seq"])
Out[28]: 2385
```

SeqRepo returns much longer sequence:

```
In [20]: from hgvs.dataproviders.seqfetcher import SeqFetcher

In [21]: sf = SeqFetcher()

In [22]: seq = sf.fetch_seq("ENST00000617537.5")

In [23]: len(seq)
Out[23]: 211554
```

**Comment by reece** [comment]
Well, that's very surprising. I'll need to investigate.

FWIW, UCSC appears to have fallen into the same issue: 
![image](https://github.com/user-attachments/assets/5628a2ab-3288-4e7d-bb74-a2b13a6ff817)
(from https://genome.cse.ucsc.edu/cgi-bin/hgGene?hgg_gene=UC032ZJW.2, taken today)

## In the meantime, this might be helpful...

Ensembl ENST ids do not refer to a sequence uniquely. The clearest current example of this is that they use the same ids in the cdna and cds fasta file, which of course are different sequences. You can test this with code like what you provided above, changing cdna to cds. The problem is not that the sequences are different, but rather that the different sequences have the same id.

In addition to the cds v. cdna issue, sequences associated with *versioned* identifiers from Ensembl were not always stable across releases. This inconsistency made it impossible to support them meaningfully in SeqRepo or UTA. (FWIW, RefSeq had similar issues, but at a much much smaller scale.) Early versions of seqrepo stored multiple sets of ensembl sequences is different namespaces, which wasted tons of space for the alias table because the ids were mostly associated uniquely with a sequence. So, I collapsed those into a single ensembl namespace.

I'm not trying to throw stones, but rather just present a critical fact that is counter to most people's assumptions: the two most prominent sources of sequences did -- and, with your observation, may still -- not guarantee that identifiers refer to a single sequence for all time. :-/

**Comment by reece** [comment]
Okay, found it. Not a bug. Ensembl itself returns this sequence:

```
❯ curl -s -H "accept: application/json" 'https://rest.ensembl.org/sequence/id/ENST00000617537' | jq -r .seq | wc  -c
211555
```
 
(+1 char for the newline)

Also, the code path that you're using is bioutils.seqfetcher, via hgvs dataproviders.

I double checked seqrepo and it's fine:

```
❯ seqrepo  -r /usr/local/share/seqrepo  start-shell -i latest 
Python 3.12.3 (main, Sep 11 2024, 14:17:37) [GCC 13.2.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.27.0 -- An enhanced Interactive Python. Type '?' for help.


seqrepo (https://github.com/biocommons/biocommons.seqrepo/)
version: 0.6.9
instance path: /usr/local/share/seqrepo/latest

>>> q=sr["ENST00000617537.5"]
>>> len(q)
2385

>>> q = bioutils.seqfetcher.fetch_seq("ENST00000617537.5")
>>> len(q)
211554

```

**Comment by davmlaw** [comment]
@reece  the Ensembl REST API endpoint  https://rest.ensembl.org/documentation/info/sequence_id

has an argument ```type``` which:

> Defaults to genomic where applicable, i.e. not translations. cdna refers to the spliced transcript sequence with UTR; cds refers to the spliced transcript sequence without UTR.

If you look, I'm using ```type=cdna``` - while when you leave it off, you're using genomic - which explains the difference.

So should SeqRepo should use the cdna rather than genomic? That looks like how it's done with RefSeq?
