### ISSUE TITLE
Seqrepo docker image install problem

### ISSUE THREAD

**Issue by roysomak4** [biocommons/biocommons.seqrepo#27]
I am trying to spin up a container from the seqrepo image from docker hub and getting the error below.
The image pulls fine. I get the same error with the other image tag as well (20161004).
Thanks.

`docker run --name seqrepo_test1 biocommons/seqrepo:20161213`

Traceback (most recent call last):
  File "/usr/local/bin/seqrepo", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/biocommons/seqrepo/cli.py", line 436, in main
    opts.func(opts)
  File "/usr/local/lib/python3.5/dist-packages/biocommons/seqrepo/cli.py", line 301, in pull
    raise KeyError("{}: not in list of remote instance names".format(instance_name))
KeyError: '20161213: not in list of remote instance names'

**Comment by reece** [comment]
Around 2017-01-01, I changed the date format to hyphen-separated. The older non-hyphenated instances were in a different download directory. I merged these so that that you should be able to fetch old and new instances, and so that old instances would also be available with new names if desired.

Also, you probably want to be using a newer seqrepo instance.

Sorry about the problem.

Note to self: changing this format definitely wasn't worth the effort! :-/

**Comment by roysomak4** [comment]
Thank you, Reece! I figured this issue couple months back and created my own custom seqrepo image using the seqrepo data from http://dl.biocommons.org/seqrepo/2017-11-18/. Sorry for my lack of time to post my workaround. 
It was a good learning exercise!
