### ISSUE TITLE
Can't install on Windows due to pysam dependency

### ISSUE THREAD

**Issue by khmccurdy** [biocommons/biocommons.seqrepo#32]
The pysam library currently does not support Windows, which creates issues when attempting to install seqrepo and libraries that use it. (Such as hgvs - https://github.com/biocommons/hgvs/issues/522)
Possible workaround may be to use [pysam-win](https://pypi.org/project/pysam-win/).

**Comment by reece** [comment]
@khmccurdy: We'll drop the seqrepo requirement for hgvs so that you can install hgvs at least. See biocommons/hgvs#522. 

For this issue specifically -- getting serepo working on windows -- I'll gladly take a PR for code or installation instructions, but I won't put any time into. Frankly, Windows just isn't used in this space enough to make it worth much effort, especially since a docker image or virtual machine will (er, should) work on Windows.

**Comment by reece** [comment]
Closing. Pysam won't ever work on Windows natively.
